server:
  port: 8083

spring:
  application:
    name: balances-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
  profiles:
    active: local



  