services:

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - lan-network
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: kafka-docker-cluster-1
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_SECURITY_PROTOCOL: PLAINTEXT
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c 'echo > /dev/tcp/127.0.0.1/9092' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 40s
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
        POSTGRES_HOST_AUTH_METHOD: trust        
    command: postgres -c config_file=/home/config/postgres.conf
    networks:
      - lan-network
    ports:
        - 5432:5432
    volumes:
        - ./postgres/postgres.conf:/home/config/postgres.conf
        - postgresdata:/var/lib/postgresql
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready']
        interval: 10s
        timeout: 5s
        retries: 10

  bff:
    container_name: bff 
    image: ${DOCKER_REGISTRY-}transactions-bff
    build:
      context: ./bff/.
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      worker:
        condition: service_healthy  
    networks:
      - lan-network
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    container_name: worker 
    image: ${DOCKER_REGISTRY-}transactions-worker
    build:
      context: ./worker/.
      dockerfile: Dockerfile
    depends_on:         
      kafka:
        condition: service_healthy
      backend:
        condition: service_healthy         
    networks:
      - lan-network
    ports:
      - 8082:8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend 
    image: ${DOCKER_REGISTRY-}transactions-backend
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy 
    networks:
      - lan-network
    ports:
      - 8083:8083
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresdata:
    external: true
    name: postgresdata

networks:
  lan-network:
    driver: bridge