server:
  port: 8084

spring:
  application:
    name: transactions-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
  profiles:
    active: local

kafka:
  consumer-topic: transaction-processed
  consumer-groupid: transaction-backend-grpid
  dead-letter-topic: transaction-processed-dlt

  