spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_accounts
  kafka:
    bootstrap-servers: localhost:9092

feign:
  client:
    balance:
      url: http://localhost:8081/api/balance
