spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_accounts
  kafka:
    bootstrap-servers: kafka:29092

feign:
  client:
    balance:
      url: http://balance:8081/api/balance
