server:
  port: 8081

spring:
  application:
    name: transactions-bff
  profiles:
    active: local
  kafka:
    consumer:
      auto-offset-reset: earliest

kafka:
  producer-topic: transaction-received
  consumer-topic: transaction-processed
  consumer-groupid: transaction-bff-grpid
  dead-letter-topic: transaction-processed-dlt
  timeout: 10000