server:
  port: 8081

spring:
  application:
    name: transactions-bff
  profiles:
    active: local
  kafka:
    consumer:
      auto-offset-reset: earliest

logging:
  level:
    org:
      springframework:
        http:
          converter:
            json: DEBUG
        kafka:
          support:
            converter: DEBUG
          listener: DEBUG
        web: DEBUG
      apache:
        kafka:
          clients:
            consumer: DEBUG
    com:
      fasterxml:
        jackson:
          databind: DEBUG

kafka:
  producer-topic: transaction-received
  consumer-topic: transaction-processed
  consumer-groupid: processed-group
  dead-letter-topic: transaction-processed-dlt
  timeout: 10000