spring:
  application:
    name: poctransactions-processor
  profiles:
    active: local
    
kafka:
  producer-topic: transaction-processed
  consumer-topic: transaction-received  
  consumer-groupid: received-group
  dead-letter-topic: transaction-received-dlt


  