server:
  port: 8083

spring:
  application:
    name: transactions-balance
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
  profiles:
    active: local



  