CREATE TABLE balances (
    accountId VARCHAR(16) PRIMARY KEY,
    amount NUMERIC(18, 2) NOT NULL,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    updatedTimestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
